services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "
      php public/server.php &
      while true; do
        inotifywait -e modify,create,delete -r /var/www &&
        pkill -f 'php public/server.php';
        php public/server.php &
      done"
    networks:
      - swoole_network

networks:
  swoole_network:
    driver: bridge
