services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
      - "9502:9502"
    command: php public/websocket.php
    networks:
      - swoole_network

networks:
  swoole_network:
    driver: bridge
