services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "
      php public/server.php &
      while true; do
        inotifywait -e modify,create,delete -r /var/www &&
        pkill -f 'php public/server.php';
        php public/server.php &
      done"
    networks:
      - swoole_network

  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-phpswoole}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
        MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
      - swoole_network

networks:
  swoole_network:
    driver: bridge
